version: '3.9'
services:
  database:
    image: postgres:13.8-alpine
    container_name: db
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mkdata_clients
    ports:
      - 5432:5432
    restart: 'always'
  
  pgadmin:
    image: dpage/pgadmin4
    tty: true
    container_name: db_manager
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
    depends_on:
      - database